---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_dock: true
dockitems_remove:
  - 'App Store'
  - Calendar
  - Contacts
  - FaceTime
  - Freeform
  - Keynote
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Music
  - News
  - Notes
  - Numbers
  - Photos
  - Podcasts
  - Safari
  - Reminders
  - Pages
  - TV
dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
  - name: "Slack"
    path: "/Applications/Slack.app/"
  - name: "Spotify"
    path: "/Applications/Spotify.app/"
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
  - name: "Warp"
    path: "/Applications/Warp.app/"
  - name: "Lens"
    path: "/Applications/Lens.app/"
  - name: "Beyond Compare"
    path: "/Applications/Beyond Compare.app/"
  - name: "System Preferences"
    path: "/System/Applications/System Settings.app/"

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/colinodell/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Projects/dotfiles
dotfiles_files:
  - .aliases
  - .config/starship.toml
  - .exports
  - .gitconfig
  - .gitignore
  - .osx
  - .vimrc
  - .zsh
  - .zshrc

homebrew_installed_packages:
  - check-ssl
  - coreutils
  - curl
  - ddev
  - dive
  - git
  - github/gh/gh
  - go
  - goreleaser
  - gpg
  - gradle
  - htop
  - imagemagick
  - jq
  - kubernetes-cli
  - ncdu
  - openjdk
  - nmap
  - node
  - nvm
  - pgcli
  - pkg-config
  - php
  - pv
  - python@3.9
  - ssh-copy-id
  - sshpass
  - sqlite
  - starship
  - tree
  - watch
  - wget
  - yq

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - colinodell/tap
  - drud/ddev
  - goreleaser/tap
  - hudochenkov/sshpass

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - altair-graphql-client
  - beyond-compare
  - docker
  - dropbox
  - elgato-stream-deck
  - flameshot
  - font-jetbrains-mono-nerd-font
  - google-chrome
  - gpg-suite-no-mail
  - iterm2
  - jetbrains-toolbox
  - joplin
  - lens
  - maccy
  - ngrok
  - obs
  - rectangle
  - sensiblesidebuttons
  - slack
  - spotify
  - stats
  - warp

# https://edge.elgato.com/egc/macos/sd/Stream_Deck_5.2.0.14948.pkg

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 937984704, name: "Amphetamine" }
mas_email: "colinodell@gmail.com"
mas_password: ""
mas_signin_dialog: true

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
  - name: ansible
  - name: passlib
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A
pecl_packages:
  - imagick
  - redis
  - xdebug


composer_home_owner: codell
composer_home_group: staff

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
