---
- name: "Check if oh-my-zsh exists"
  stat:
    path: "{{ lookup('env','HOME') }}/.oh-my-zsh"
  register: oh_my_zsh

- name: "Download oh-my-zsh installer"
  get_url:
    url: "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    dest: "/tmp/install-oh-my-zsh.sh"
    mode: "755"
  when: not oh_my_zsh.stat.exists

- name: "Install oh-my-zsh"
  shell: "/tmp/install-oh-my-zsh.sh"
  when: not oh_my_zsh.stat.exists
