---

- name: Check if vault cli installed
  ansible.builtin.stat:
    path: /usr/local/bin/vault
  register: vault_cli

- name: Download and vault cli
  ansible.builtin.unarchive:
    src: "{{ vault_cli_url }}"
    dest: /usr/local/bin
    remote_src: yes
  when: not vault_cli.stat.exists
  become: yes

- name: Make vault cli executable
  ansible.builtin.file:
    path: /usr/local/bin/vault
    mode: '0755'
  become: yes
